config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  resources :goals

  # root "goals#index"

  root "home#home"
  get "goals", to: "goals#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy
  has_many :goals, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :authenticate

 def authenticate
    Current.user = User.find_by(id: session[:user_id]) if session[:user_id]

    # @user_email = Current.user.email_address
  end

 def after_authentication_url
   goals_path
 end

end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController 
  before_action :set_goal, only: %i[ show edit update destroy ]

  # GET /goals or /goals.json
  def index
    @goals = Current.user.goals
  end

  # GET /goals/1 or /goals/1.json
  def show
    @goal = Current.user.goals.find(params[:id])
  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
    @goal = Current.user.goals.find(params[:id])
  end

  # POST /goals or /goals.json
  def create
    # @goal = Goal.new(goal_params)

    @goal = Current.user.goals.new(goal_params)

    respond_to do |format|
      if @goal.save
        format.html { redirect_to @goal, notice: "Goal was successfully created." }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1 or /goals/1.json
  def update

    @goal = Current.user.goals.find(params[:id])

    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to @goal, notice: "Goal was successfully updated." }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1 or /goals/1.json
  def destroy
    @goal = Current.user.goals.find(params[:id])

    @goal.destroy!

    respond_to do |format|
      format.html { redirect_to goals_path, status: :see_other, notice: "Goal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def goal_params
      params.expect(goal: [ :goal, :details, :date, :accomplished ])
    end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  allow_unauthenticated_access only: %i[ home ]
  before_action :resume_session, only: %i[home]



  def home
  end

end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  allow_unauthenticated_access

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      start_new_session_for @user
      redirect_to root_path, notice: 'Successfully signed up!'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email_address, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/goals/_form.html.erb
<%= form_with(model: goal) do |form| %>
  <% if goal.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
        <% goal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :goal, style: "display: block" %>
    <%= form.text_field :goal %>
  </div>

  <div>
    <%= form.label :details, style: "display: block" %>
    <%= form.textarea :details %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :accomplished, style: "display: block" %>
    <%= form.checkbox :accomplished %>
  </div> 

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/goals/_goal.html.erb
<div id="<%= dom_id goal %>">
  <p>
    <strong>Goal:</strong>
    <%= goal.goal %>
  </p>

  <p>
    <strong>Details:</strong>
    <%= goal.details %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= goal.date %>
  </p>

  <p>
    <strong>Accomplished:</strong>
    <%= goal.accomplished %>
  </p>

</div>

app/views/goals/edit.html.erb
<% content_for :title, "Editing goal" %>

<h1>Editing goal</h1>

<%= render "form", goal: @goal %>

<br>

<div>
  <%= link_to "Show this goal", @goal %> |
  <%= link_to "Back to goals", goals_path %>
</div>

app/views/goals/home.html.erb
<h1>Create some goals!</h1>

app/views/goals/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Goals" %>

<h1>Goals</h1>

<div id="goals">
  <% @goals.each do |goal| %>
    <%= render goal %>
    <p>
      <%= link_to "Show this goal", goal %>
    </p>
  <% end %>
</div>

<%= link_to "New goal", new_goal_path %>

app/views/goals/new.html.erb
<% content_for :title, "New goal" %>

<h1>New goal</h1>

<%= render "form", goal: @goal %>

<br>

<div>
  <%= link_to "Back to goals", goals_path %>
</div>

app/views/goals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @goal %>

<div>
  <%= link_to "Edit this goal", edit_goal_path(@goal) %> |
  <%= link_to "Back to goals", goals_path %>

  <%= button_to "Destroy this goal", @goal, method: :delete %>
</div>

app/views/layouts/_header.html.erb
<p><%= link_to "Home", root_path %></p>
<p><%= link_to "Goals", goals_path %></p>


<% if Current.user.present? %>
  <p><%= Current.user.email_address %></p>
<% end %>


<%= link_to "Login", new_session_path unless authenticated? %>
<%= button_to "Log Out", session_path, method: :delete if authenticated? %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Goals" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>